-- Hustle Hall customer reviews
-- Run against the SAME Supabase project used by app.js:
-- https://ucopmutxwsrgnudsyuhz.supabase.co

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  customer_name text,
  rating smallint not null check (rating between 1 and 5),
  service text not null check (service in ('Local Ride','Student Transportation','Package Delivery','Business Delivery')),
  review_text text not null check (char_length(review_text) between 10 and 1200),
  recommend boolean not null,
  status text not null default 'pending' check (status in ('pending','approved','hidden')),
  created_at timestamptz not null default now(),
  moderated_at timestamptz,
  moderated_by uuid references auth.users(id)
);

alter table public.reviews enable row level security;

grant select, insert on table public.reviews to anon, authenticated;
grant update, delete on table public.reviews to authenticated;
grant usage, select on sequence public.reviews_id_seq to anon, authenticated;

drop policy if exists "Public can submit pending reviews" on public.reviews;
create policy "Public can submit pending reviews"
on public.reviews
for insert
to anon, authenticated
with check (
  status = 'pending'
  and moderated_at is null
  and moderated_by is null
);

drop policy if exists "Public can read approved reviews" on public.reviews;
create policy "Public can read approved reviews"
on public.reviews
for select
to anon, authenticated
using (status = 'approved');

drop policy if exists "Admins can read all reviews" on public.reviews;
create policy "Admins can read all reviews"
on public.reviews
for select
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid())
      and p.role = 'admin'
  )
);

drop policy if exists "Admins can moderate reviews" on public.reviews;
create policy "Admins can moderate reviews"
on public.reviews
for update
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid())
      and p.role = 'admin'
  )
)
with check (
  status in ('pending','approved','hidden')
  and exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid())
      and p.role = 'admin'
  )
);

drop policy if exists "Admins can delete reviews" on public.reviews;
create policy "Admins can delete reviews"
on public.reviews
for delete
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid())
      and p.role = 'admin'
  )
);

create index if not exists reviews_status_created_at_idx
  on public.reviews (status, created_at desc);
