const OPS_STATUSES=['Requested','Confirmed','Scheduled','In Progress','Awaiting Client','Driver Assigned','Driver En Route','Picked Up','In Transit','Delivered','Completed','Cancelled','Rejected'];
let opsRows=[];
const q=(selector)=>document.querySelector(selector);
const clean=(value)=>String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const dollars=(value)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value)||0);
const number=(value)=>Number(value)||0;
const sourceFor=(order)=>order.payload?.source==='BuildIt'||order.service==='buildit'?'BuildIt':'HustleHall';
const payloadFor=(order)=>order.payload||{};
function normalize(order){const p=payloadFor(order);const revenue=number(p.revenue??p.quotedRevenue??order.total);const collected=number(p.collected);const costs=number(p.costs);return{raw:order,id:order.id,source:sourceFor(order),status:order.status||p.status||'Requested',customer:p.customerName||p.name||'Customer',phone:p.phone||'',email:p.email||'',service:p.jobType||p.serviceName||p.services||order.service||'Booking',created:order.created_at||p.createdAt||'',scheduled:p.scheduledAt||[p.date,p.time].filter(Boolean).join(' '),progress:number(p.progress),revenue,collected,costs,profit:revenue-costs,nextAction:p.nextAction||'',notes:p.notes||p.details||p.projectDetails||'',payload:p};}
function filtered(){const source=q('[data-filter-source]').value;const status=q('[data-filter-status]').value;const term=q('[data-filter-search]').value.trim().toLowerCase();return opsRows.filter(r=>(!source||r.source===source)&&(!status||r.status===status)&&(!term||[r.id,r.customer,r.service,r.phone,r.email].join(' ').toLowerCase().includes(term)));}
function stats(rows){const revenue=rows.reduce((sum,r)=>sum+r.revenue,0);const collected=rows.reduce((sum,r)=>sum+r.collected,0);const profit=rows.reduce((sum,r)=>sum+r.profit,0);const active=rows.filter(r=>!['Completed','Delivered','Cancelled','Rejected'].includes(r.status)).length;q('[data-ops-stats]').innerHTML=[[rows.length,'Bookings'],[active,'Active jobs'],[dollars(revenue),'Revenue booked'],[dollars(collected),'Collected'],[dollars(profit),'Gross profit']].map(([value,label])=>`<article class="ops-card"><span>${label}</span><strong>${value}</strong></article>`).join('');}
function render(){const rows=filtered();stats(rows);q('[data-ops-rows]').innerHTML=rows.length?rows.map(r=>`<tr data-row="${clean(r.id)}"><td><span class="ops-source ${r.source==='BuildIt'?'buildit':''}">${r.source}</span><br><strong>${clean(r.id)}</strong><br><small>${clean(r.created)}</small></td><td><strong>${clean(r.customer)}</strong><br>${clean(r.service)}<br><small>${clean(r.phone)} ${clean(r.email)}</small><br><small>${clean(r.notes)}</small></td><td>${clean(r.scheduled||'Not scheduled')}</td><td class="ops-progress"><label>Status<select data-field="status">${OPS_STATUSES.map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select></label><label>Progress %<input data-field="progress" type="number" min="0" max="100" value="${r.progress}"></label></td><td><div class="ops-money"><label>Revenue<input data-field="revenue" type="number" min="0" step="0.01" value="${r.revenue}"></label><label>Collected<input data-field="collected" type="number" min="0" step="0.01" value="${r.collected}"></label><label>Direct costs<input data-field="costs" type="number" min="0" step="0.01" value="${r.costs}"></label><label>Balance<strong>${dollars(r.revenue-r.collected)}</strong></label></div><div class="ops-profit ${r.profit<0?'ops-negative':''}">Profit: ${dollars(r.profit)}</div></td><td><textarea data-field="nextAction" rows="3">${clean(r.nextAction)}</textarea><button class="button button-secondary ops-save" data-save>Save changes</button></td><td>${clean(r.raw.updated_at||r.created||'')}</td></tr>`).join(''):'<tr><td colspan="7" class="ops-empty">No matching bookings.</td></tr>';}
async function loadOperations(){const message=q('[data-ops-message]');message.classList.remove('is-error');message.textContent='Loading bookings from both businesses…';try{const client=await hhtSupabaseReady;const{data:{user}}=await client.auth.getUser();if(!user){location.href='admin-login.html';return;}const{data,error}=await client.from('orders').select('*').order('created_at',{ascending:false});if(error)throw error;opsRows=(data||[]).map(normalize);const statusFilter=q('[data-filter-status]');statusFilter.innerHTML='<option value="">Every status</option>'+OPS_STATUSES.map(s=>`<option>${s}</option>`).join('');message.textContent=`Connected. ${opsRows.length} booking${opsRows.length===1?'':'s'} loaded.`;render();}catch(error){message.classList.add('is-error');message.textContent=`Could not load bookings: ${error.message||error}`;}}
async function saveRow(button){const tr=button.closest('[data-row]');const item=opsRows.find(r=>r.id===tr.dataset.row);if(!item)return;button.disabled=true;button.textContent='Saving…';const value=(field)=>tr.querySelector(`[data-field="${field}"]`).value;const payload={...item.payload,source:item.source,progress:number(value('progress')),revenue:number(value('revenue')),collected:number(value('collected')),costs:number(value('costs')),nextAction:value('nextAction'),updatedAt:new Date().toISOString()};try{const client=await hhtSupabaseReady;const{error}=await client.from('orders').update({status:value('status'),total:payload.revenue,payload}).eq('id',item.id);if(error)throw error;await loadOperations();}catch(error){alert(`Changes were not saved. ${error.message||error}`);button.disabled=false;button.textContent='Save changes';}}
function exportOperations(){const headers=['Source','Booking ID','Customer','Service','Status','Progress','Revenue','Collected','Costs','Profit','Next Action'];const rows=filtered().map(r=>[r.source,r.id,r.customer,r.service,r.status,r.progress,r.revenue,r.collected,r.costs,r.profit,r.nextAction]);const csv=[headers,...rows].map(row=>row.map(value=>`"${String(value??'').replaceAll('"','""')}"`).join(',')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download='allmovingparts-operations.csv';link.click();URL.revokeObjectURL(link.href);}
document.addEventListener('click',(event)=>{if(event.target.matches('[data-save]'))saveRow(event.target);if(event.target.matches('[data-refresh]'))loadOperations();if(event.target.matches('[data-export-ops]'))exportOperations();});
document.addEventListener('input',(event)=>{if(event.target.matches('[data-filter-source],[data-filter-status],[data-filter-search]'))render();});
loadOperations();
